// client/src/views/auth/SignUp.vue
<template>
  <div class="flex flex-col items-center justify-center h-screen bg-blue-400">
    <h1 class="text-4xl text-center">SignUp</h1>
    <GithubButton />
    <form class="max-w-screen-sm w-full" @submit.prevent="onSubmit" novalidate>
      <div>
        <label for="username">Username</label>
        <Input v-model="credentials.username" id="username" text="text" />
      </div>
      <div>
        <label for="fullName">Full Name</label>
        <Input v-model="credentials.fullName" id="fullName" type="text" />
      </div>
      <div>
        <label for="email">Email</label>
        <Input v-model="credentials.email" id="email" type="email" />
      </div>
      <div>
        <label for="password">Password</label>
        <Input v-model="credentials.password" id="password" type="password" />
      </div>
      <div class="flex justify-between">
        <router-link to="/auth/login">
          Login with existing account
        </router-link>
        <button class="button">Sign Up</button>
      </div>
    </form>
  </div>
</template>

<script lang="ts">
import { Ref } from "@vue/reactivity";

import Input from "@/components/Input.vue";
import GithubButton from "@/components/GithubButton.vue";

import { useSignUp } from "@/hooks/api/auth";

interface UserCredentials {
  username: string;
  email: string;
  fullName: string;
  password: string;
}

interface Setup {
  onSubmit: () => void;
  credentials: Ref<UserCredentials>;
}

export default {
  components: {
    Input,
    GithubButton,
  },
  setup(): Setup {
    const { credentials, onSubmit } = useSignUp();

    return { onSubmit, credentials };
  },
};
</script>

<style lang="scss"></style>

// client/src/pages/auth/sign-up.tsx
import React from "react";
import { useForm } from "react-hook-form";

import Container from "@material-ui/core/Container";
import TextField from "@material-ui/core/TextField";
import Typography from "@material-ui/core/Typography";
import Button from "@material-ui/core/Button";
import { AccountCircle, Email } from "@material-ui/icons";
import InputAdornment from "@material-ui/core/InputAdornment";

import { useAuthStyles } from "../../styles/pages/auth";
import { Link } from "react-router-dom";
import { PasswordInput } from "../../components/PasswordInput";

interface Inputs {
  username: string;
  fullName: string;
  email: string;
  password: string;
}

export const SignUp: React.FC = () => {
  const { register, handleSubmit } = useForm<Inputs>();
  const classes = useAuthStyles();

  const onSubmit = (data: Inputs) => console.log(data);

  return (
    <Container className={classes.container} maxWidth="sm">
      <Typography
        className={classes.header}
        variant="h4"
        align="center"
        component="h1"
      >
        Create An Account
      </Typography>
      <form
        onSubmit={handleSubmit(onSubmit)}
        className={classes.form}
        noValidate
      >
        <TextField
          fullWidth
          id="outlined-basic"
          label="Username"
          variant="outlined"
          className={classes.input}
          {...register("username")}
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <AccountCircle />
              </InputAdornment>
            ),
          }}
        />
        <TextField
          fullWidth
          id="outlined-basic"
          label="Full Name"
          variant="outlined"
          className={classes.input}
          {...register("fullName")}
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <AccountCircle />
              </InputAdornment>
            ),
          }}
        />
        <TextField
          fullWidth
          id="outlined-basic"
          label="Email"
          variant="outlined"
          className={classes.input}
          {...register("email")}
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <Email />
              </InputAdornment>
            ),
          }}
        />
        <PasswordInput ref={register("password")} />
        <div className={classes.bottom}>
          <span>
            Already have an account?
            <Link to="/auth/login">Log in</Link>
          </span>
          <Button type="submit" variant="contained">
            Sign Up!
          </Button>
        </div>
      </form>
    </Container>
  );
};
